# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c070f90211adec766034d32db5ca8855da1cb119e4eeec4c84c8a785431f631cbfcb08336362229810240585ce4c3317488c00f21272b45a0cd900cdf299cf11

test:
  secret_key_base: 1919717321504c5314b9bdf5f781d70ea7f48d68d71035cddc6f4310059fa60619bf7b72be030c1d468792c6dfca8725c7993a474ac9a2a652c0a615880190f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
